name: eclipse-temurin-17-focal

on:
  push:
    branches:
    - master
    paths:
      - "eclipse-temurin-17-focal/**"
      - .github/workflows/eclipse-temurin-17-focal.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"
  pull_request:
    paths:
      - "eclipse-temurin-17-focal/**"
      - .github/workflows/eclipse-temurin-17-focal.yml
      - .github/workflows/_template.yml
      - common.sh
      - tags-for-dir.sh
      - "tests/**"
      - "!tests/*.ps*"
      - "!tests/*.windows"

jobs:
  build:
    uses: ./.github/workflows/_template.yml
    with:
      directory: eclipse-temurin-17-focal
    secrets: inherit
